// GENERATED by scripts/embed-migrations.mjs — do not edit by hand.
// Run `pnpm --filter @nexestra/storage db:generate` after changing src/schema.ts.

export interface Migration {
  tag: string;
  statements: readonly string[];
}

export const MIGRATIONS: readonly Migration[] = [
  {
    tag: "0000_init",
    statements: [
      "CREATE TABLE `approvals` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`taskId` text,\n\t`runId` text,\n\t`kind` text NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`risk` text DEFAULT 'low' NOT NULL,\n\t`status` text NOT NULL,\n\t`requestedAt` text NOT NULL,\n\t`resolvedAt` text,\n\t`resolvedBy` text,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `approvals_workspace_idx` ON `approvals` (`workspaceId`,`status`);",
      "CREATE TABLE `artifacts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`taskId` text,\n\t`runId` text,\n\t`kind` text NOT NULL,\n\t`title` text NOT NULL,\n\t`path` text NOT NULL,\n\t`mimeType` text DEFAULT 'text/plain' NOT NULL,\n\t`sizeBytes` integer DEFAULT 0 NOT NULL,\n\t`preview` text DEFAULT '' NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `artifacts_thread_idx` ON `artifacts` (`threadId`);",
      "CREATE TABLE `events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text,\n\t`runId` text,\n\t`seq` integer NOT NULL,\n\t`type` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`createdAt` text NOT NULL\n);",
      "CREATE INDEX `events_thread_seq_idx` ON `events` (`threadId`,`seq`);",
      "CREATE INDEX `events_workspace_seq_idx` ON `events` (`workspaceId`,`seq`);",
      "CREATE TABLE `memories` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text,\n\t`type` text NOT NULL,\n\t`title` text NOT NULL,\n\t`content` text DEFAULT '' NOT NULL,\n\t`source` text,\n\t`tags` text NOT NULL,\n\t`authoredBy` text DEFAULT 'master' NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `memories_workspace_idx` ON `memories` (`workspaceId`);",
      "CREATE TABLE `memory_links` (\n\t`sourceId` text NOT NULL,\n\t`targetId` text NOT NULL,\n\t`type` text NOT NULL,\n\t`note` text DEFAULT '' NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`createdAt` text NOT NULL,\n\tPRIMARY KEY(`sourceId`, `targetId`, `type`)\n);",
      "CREATE INDEX `memory_links_target_idx` ON `memory_links` (`targetId`);",
      "CREATE TABLE `messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`role` text NOT NULL,\n\t`content` text NOT NULL,\n\t`references` text NOT NULL,\n\t`toolCalls` text NOT NULL,\n\t`attachments` text NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `messages_thread_idx` ON `messages` (`threadId`,`createdAt`);",
      "CREATE TABLE `plans` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`specId` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`summary` text DEFAULT '' NOT NULL,\n\t`taskIds` text NOT NULL,\n\t`edges` text NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `plans_thread_idx` ON `plans` (`threadId`);",
      "CREATE TABLE `run_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`runId` text NOT NULL,\n\t`seq` integer NOT NULL,\n\t`type` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`createdAt` text NOT NULL\n);",
      "CREATE INDEX `run_events_run_idx` ON `run_events` (`runId`,`seq`);",
      "CREATE TABLE `runs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`taskId` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`harness` text NOT NULL,\n\t`sessionRef` text,\n\t`worktreePath` text,\n\t`status` text NOT NULL,\n\t`exitCode` integer,\n\t`usage` text NOT NULL,\n\t`startedAt` text NOT NULL,\n\t`endedAt` text,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `runs_thread_idx` ON `runs` (`threadId`,`startedAt`);",
      "CREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE TABLE `specs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`goal` text NOT NULL,\n\t`scope` text NOT NULL,\n\t`constraints` text NOT NULL,\n\t`expectedOutcome` text DEFAULT '' NOT NULL,\n\t`acceptanceCriteria` text NOT NULL,\n\t`openQuestions` text NOT NULL,\n\t`decisions` text NOT NULL,\n\t`frozen` integer DEFAULT false NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `specs_thread_idx` ON `specs` (`threadId`);",
      "CREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`threadId` text NOT NULL,\n\t`planId` text NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`dependsOn` text NOT NULL,\n\t`assignedHarness` text,\n\t`harnessConfig` text NOT NULL,\n\t`status` text NOT NULL,\n\t`attempts` integer DEFAULT 0 NOT NULL,\n\t`maxAttempts` integer DEFAULT 3 NOT NULL,\n\t`acceptanceCriteriaIds` text NOT NULL,\n\t`costUSD` real DEFAULT 0 NOT NULL,\n\t`order` integer DEFAULT 0 NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `tasks_thread_idx` ON `tasks` (`threadId`,`order`);",
      "CREATE TABLE `threads` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspaceId` text NOT NULL,\n\t`title` text NOT NULL,\n\t`phase` text NOT NULL,\n\t`summary` text DEFAULT '' NOT NULL,\n\t`specId` text,\n\t`planId` text,\n\t`budgetUSD` real DEFAULT 20 NOT NULL,\n\t`costUSD` real DEFAULT 0 NOT NULL,\n\t`lastActivityAt` text NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
      "CREATE INDEX `threads_workspace_idx` ON `threads` (`workspaceId`);",
      "CREATE TABLE `workspaces` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`rootPath` text NOT NULL,\n\t`shortLabel` text NOT NULL,\n\t`defaultBranch` text DEFAULT 'main' NOT NULL,\n\t`settings` text NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`updatedAt` text NOT NULL\n);",
    ],
  },
  {
    tag: "0001_task_merge_state",
    statements: ["ALTER TABLE `tasks` ADD `mergeState` text;"],
  },
];
